name: "\U0001F41B Bug Report"
description: Signaler un bug
title: "[Bug] "
labels: ["bug"]
body:
  - type: dropdown
    id: module
    attributes:
      label: Module
      description: Quel module est concerné ?
      options:
        - Auth
        - Group
        - Bank Account
        - Budget
        - Operation
        - Infra
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description du bug
      description: Décris clairement le problème rencontré
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Étapes pour reproduire
      description: Liste les étapes pour reproduire le bug
      placeholder: |
        1. Aller sur ...
        2. Cliquer sur ...
        3. Observer ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Comportement attendu
      description: Que devrait-il se passer ?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Comportement actuel
      description: Que se passe-t-il réellement ?
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Captures d'écran
      description: Si applicable, ajoute des captures d'écran
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Sévérité
      options:
        - P0 - Bloquant
        - P1 - Majeur
        - P2 - Mineur
        - P3 - Cosmétique
    validations:
      required: true
