name: "\U0001F680 Feature"
description: Nouvelle fonctionnalité à développer
title: "[Feature] "
labels: ["feature"]
body:
  - type: dropdown
    id: module
    attributes:
      label: Module
      description: Quel module est concerné ?
      options:
        - Auth
        - Group
        - Bank Account
        - Budget
        - Operation
        - Infra
    validations:
      required: true

  - type: textarea
    id: user-story
    attributes:
      label: User Story
      description: Décris la fonctionnalité du point de vue utilisateur
      placeholder: |
        En tant que [rôle],
        je veux [action],
        afin de [bénéfice].
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Critères d'acceptation
      description: Liste les conditions pour considérer cette feature comme terminée
      placeholder: |
        - [ ] Critère 1
        - [ ] Critère 2
        - [ ] Critère 3
    validations:
      required: true

  - type: textarea
    id: technical-tasks
    attributes:
      label: Tâches techniques
      description: Découpage technique de l'implémentation
      placeholder: |
        - [ ] Backend : ...
        - [ ] Frontend : ...
        - [ ] Tests : ...
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priorité
      options:
        - P0 - Critical
        - P1 - High
        - P2 - Medium
        - P3 - Low
    validations:
      required: true

  - type: dropdown
    id: size
    attributes:
      label: Effort estimé
      options:
        - XS (< 1h)
        - S (demi-journée)
        - M (1 jour)
        - L (2-3 jours)
        - XL (1 semaine+)
    validations:
      required: false
