name: "\U0001F6A8 Hotfix"
description: Correction urgente en production
title: "[hotfix] "
labels: ["hotfix"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Décris le problème rencontré et comment le reproduire
      placeholder: |
        Description du bug...

        Étapes pour reproduire :
        1. Aller sur ...
        2. Cliquer sur ...
        3. Observer ...
    validations:
      required: false
