name: "\U0001F3A8 Style"
description: Formatage du code source, lint (aucun changement fonctionnel ni visuel)
title: "[style] "
labels: ["style"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Décris les changements de style à apporter
    validations:
      required: false
